### ISSUE TITLE
Error in fixtures:load --append

### ISSUE THREAD

**Issue by asaurina** [inshopgroup/inshop-crm-api#3]
When i try execute that command ` php bin/console doctrine:fixtures:load --append ` show a error:

>    > loading App\DataFixtures\CountryFixtures
> 
> In Http.php line 190:
> 
>   Couldn't resolve host
> 
> 
> doctrine:fixtures:load [--append] [--group GROUP] [--em EM] [--shard SHARD] [--purge-with-truncate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

I am using Windows 10, all commands work but when the setup reaches `doctrine: fixtures: load --append` it breaks

**Comment by inshop** [comment]
Looks like elasticsearch is down. If you're using docker-compose try to check status `docker-compose ps`

**Comment by inshop** [comment]
Issue is not related to inshop crm api

**Comment by asaurina** [comment]
> 
> 
> Issue is not related to inshop crm api

Ya, is not a issue related to inshop, but can u help me? maybe a idea... thanks.

![error-windows](https://user-images.githubusercontent.com/3385024/70001903-7e4de580-152c-11ea-9a73-ed34030bf346.png)

**Comment by inshop** [comment]
All your containers have Exit state, try to check logs `docker-compose logs`
